name: Build Project

on:
  workflow_call:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install dependencies
      run: npm install

    - name: Run end-to-end tests
      run: npm run test

    - name: Build
      run: |
        if [ "${{ inputs.env }}" == "production" ]; then
          npm run build --prod
        else
          npm run build
        fi
