name: Create Release Tag

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  create-release-tag:
    name: Create Release Tag
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Tag release
      run: |
        VERSION=$(cat package.json | grep '"version"' | sed 's/.*: "\(.*\)".*/\1/')
        git tag "Bo@$VERSION"
        git push origin --tags
