name: Deploy to Production

on:
  push:
    branches:
      - main

jobs:
  build-project:
    uses: ./.github/workflows/build-project.yml
    with:
      environment: production

  create-release-tag:
    needs: build-project
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Tag release
      run: |
        VERSION=$(cat package.json | grep '"version"' | sed 's/.*: "\(.*\)".*/\1/')
        git tag "Bo@$VERSION"
        git push origin --tags
