name: Pull request - Production

on:
  pull_request:
    branches:
      - main

jobs:
  pull-request-main:
    name: Pull request - Production
    uses: ./.github/workflows/build-project.yml
    with:
      environment: production
