name: Pull request - Development

on:
  pull_request:
    branches:
      - develop

jobs:
  pull-request-develop:
    name: Pull request - Development
    uses: ./.github/workflows/build-project.yml
    with:
      environment: development
