name: Pull request - Development

on:
  pull_request:
    branches:
      - develop

jobs:
  build-and-deploy:
    uses: ./.github/workflows/build-project.yml
    with:
      environment: development
